application: vavpush
version: 2
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: "lxml"
  version: "latest"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/card.html
  static_files: static/card.html
  upload: static/card.html
  http_headers:
    Access-Control-Allow-Origin: http://vk.com

- url: /static
  static_dir: static

- url: .*
  script: main.app
